### ISSUE TITLE
E: Unable to locate package nvidia-docker2

### ISSUE THREAD

**Issue by gdamion** [be2rlab/yaprofi_robotics_2020#2]
Здравствуйте!
В конце работы скрипта docker/nvidia/install_docker.bash выдавалась ошибка в заголовке, и соответственно билдить не удавалось. Я решил это, добавив репозитории на закачку данного пакета в Dockerfile:
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

Полагаю, из-за этого не только у меня могло не заработать.

**Comment by kirillin** [comment]
Спасибо, добавлю.

Ошибка была при сборке контейнера? На каком шаге не помните?
